project_id = "irraxbjzwyetwicidqdv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.check-invite]
    verify_jwt = false
  [functions.evaluate-session]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-invite]
    verify_jwt = false
  [functions.speak]
    verify_jwt = false
  [functions.training-chat]
    verify_jwt = false
  [functions.transcribe]
    verify_jwt = false
